  - name: Install mysql
    apt: name=mysql-server

  - name: Install python-mysqldb
    apt: name=python-mysqldb

  - name: Create database
    mysql_db: name={{ mysqldb }}

  - name: Create DB user
    mysql_user: name={{ mysqlusr }} password={{ mysqlass }} priv=*.*:ALL
